import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { WEEK2 } from "./week2.ts";

const ENGINE_VERSION="GC-W2-V4.0.0", DATA_VERSION="POWER_1B-W1-121+CHAIRMAN_OVR", WEEK_KEY="2026-W02";
const CONSOLE_URL="https://rgbslb11.github.io/Synthcast-Console/v4/", SPEEDS=[1,4,10,50];
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-operator-token","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Cache-Control":"no-store"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json; charset=utf-8"}});
const clamp=(lo:number,v:number,hi:number)=>Math.max(lo,Math.min(v,hi));
const randHex=(n:number)=>Array.from(crypto.getRandomValues(new Uint8Array(n)),b=>b.toString(16).padStart(2,"0")).join("");
const sha256=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,"0")).join("");
const now=()=>new Date().toISOString();
type Game=Record<string,any>;

type Poss={team:0|1,result:string,points:number,beforeClock:number,clockSeconds:number,remainingClockSeconds:number};
function seedWords(seed:string,id:string,run:number){const t=`${seed}|${id}|${run}`;let a=0x9e3779b9,b=0x243f6a88,c=0xb7e15162,d=0xdeadbeef;for(let i=0;i<t.length;i++){const x=t.charCodeAt(i);a=Math.imul(a^x,2654435761)>>>0;b=Math.imul(b^x,1597334677)>>>0;c=Math.imul(c^x,2246822519)>>>0;d=Math.imul(d^x,3266489917)>>>0}return[a||1,b||2,c||3,d||4]}
function rnd(g:Game){let[a,b,c,d]=g.rngState as number[];const t=(a+b+d)>>>0;d=(d+1)>>>0;a=(b^(b>>>9))>>>0;b=(c+(c<<3))>>>0;c=((c<<21)|(c>>>11))>>>0;c=(c+t)>>>0;g.rngState=[a,b,c,d];return t/4294967296}
const elo=(p:number)=>1031.6+1208.9*p;
const total=(g:Game,t:0|1)=>Object.values(g.scores??{}).reduce((s:number,q:any)=>s+(q?.[t]??0),0);
const runId=(id:string,n:number)=>`${id}-R${String(n).padStart(2,"0")}`;
function initialGame(s:any):Game{const seedHex=randHex(16),runNumber=1;return{...s,away:{name:s.away,record:""},home:{name:s.home,record:""},lifecycle:"UNLAUNCHED",activity:"UPCOMING",auto:false,onAir:false,operatorPaused:false,quarterLengthSeconds:600,scoreboardSeconds:600,elapsedSeconds:0,period:"1st",activePeriod:"1",otCount:0,speed:1,scores:{"1":[0,0],"2":[0,0],"3":[0,0],"4":[0,0]},possession:0,ballSide:"OWN",yardline:25,down:1,distance:"10",breakSeconds:0,breakLabel:"",deadBallSeconds:0,pendingPeriod:"",pendingPossession:null,tvBreaksTaken:[],seedHex,rngState:seedWords(seedHex,s.id,runNumber),seedLocked:false,runNumber,runId:runId(s.id,runNumber),runHistory:[],createdRunAt:now(),launchedAt:null,completedAt:null,history:[],lastPlay:s.autoEligible?"Ready for launch · POWER 1B · V4":"Ready for launch · AUTO blocked: POWER 1B unavailable",locked:false}}
function score(g:Game,t:0|1,pts:number,source="SIM"){const k=g.activePeriod,cur=g.scores[k]??[0,0],n:[number,number]=[Number(cur[0]||0),Number(cur[1]||0)];n[t]+=pts;g.scores[k]=n;g.history.push({ts:g.elapsedSeconds,period:k,team:t,points:pts,source})}
function thresholds(g:Game){const q=g.quarterLengthSeconds,p=g.period;if(p==="1st"||p==="3rd")return[[Math.round(q*.75),180,"Scheduled TV timeout"],[Math.round(q*.475),180,"Scheduled TV timeout"],[Math.round(q*.25),180,"Scheduled TV timeout"],[120,180,"Scheduled TV timeout"]];return[[Math.round(q*.75),180,"Scheduled TV timeout"],[Math.round(q*.5),180,"Scheduled TV timeout"],[120,150,"Two-minute timeout"]]}
const periodKey=(p:string)=>p==="1st"?"1":p==="2nd"?"2":p==="3rd"?"3":"4";
function maybeBreak(g:Game,before:number,after:number){for(const[th,dur,label]of thresholds(g) as[number,number,string][]) {const k=`${g.period}-${th}`;if(before>th&&after<=th&&!g.tvBreaksTaken.includes(k)){g.tvBreaksTaken.push(k);g.breakSeconds=dur;g.breakLabel=label;g.activity="BREAK";return true}}return false}
function startOT(g:Game){g.otCount++;g.period=g.otCount===1?"OT":`${g.otCount}OT`;g.activePeriod=g.period;g.scores[g.activePeriod]=[0,0];const first=rnd(g)<.5?0:1,second=first===0?1:0;const op=()=>{if(g.otCount>=3)return rnd(g)<.48?2:0;const r=rnd(g);if(r<.5)return g.otCount===2?8:7;if(r<.72)return 3;return 0};const a=op(),b=op();score(g,first as 0|1,a);score(g,second as 0|1,b);g.elapsedSeconds+=180;g.lastPlay=`${g.period} complete · ${a}-${b}`;if(total(g,0)!==total(g,1)){g.lifecycle="FINAL_PENDING";g.activity="FINAL";g.auto=false;g.completedAt=now()}else{g.breakSeconds=60;g.breakLabel="Extra-period break";g.activity="BREAK";g.pendingPeriod="OT"}}
function finishPeriod(g:Game){g.pendingPossession=null;g.deadBallSeconds=0;if(g.period==="1st"){g.pendingPeriod="2nd";g.breakSeconds=255;g.breakLabel="End 1st · 04:15";g.activity="BREAK";return}if(g.period==="2nd"){g.pendingPeriod="3rd";g.breakSeconds=1200;g.breakLabel="Halftime · 20:00";g.activity="BREAK";return}if(g.period==="3rd"){g.pendingPeriod="4th";g.breakSeconds=255;g.breakLabel="End 3rd · 04:15";g.activity="BREAK";return}if(total(g,0)===total(g,1)){startOT(g);return}g.lifecycle="FINAL_PENDING";g.activity="FINAL";g.auto=false;g.completedAt=now();g.lastPlay=`Final · ${total(g,0)}-${total(g,1)} · awaiting operator lock`}
function advancePeriod(g:Game){if(!g.pendingPeriod){g.activity="LIVE";return}const p=g.pendingPeriod;g.pendingPeriod="";g.breakLabel="";g.activity="LIVE";if(p==="OT"){startOT(g);return}g.period=p;g.activePeriod=periodKey(p);g.scoreboardSeconds=g.quarterLengthSeconds;if(p==="3rd"){g.possession=1;g.lastPlay="Second-half kickoff"}else g.lastPlay=`${p} quarter begins`}
function beginPoss(g:Game){const t=g.possession as 0|1,own=t===0?g.awayPower1B:g.homePower1B,opp=t===0?g.homePower1B:g.awayPower1B;if(own==null||opp==null){g.auto=false;g.lastPlay="AUTO blocked · POWER 1B missing";return}let edge=elo(own)-elo(opp);if(!g.neutral)edge+=t===1?65:-65;const td=clamp(.08,.205+edge/2400,.38),fg=clamp(.045,.095+edge/6000,.16),to=clamp(.055,.105-edge/7000,.16),r=rnd(g);let result="Punt",points=0;if(r<td){result="Touchdown";points=7}else if(r<td+fg){result="Field goal";points=3}else if(r<td+fg+to)result="Turnover";const base=70+Math.floor(rnd(g)*61),clock=Math.max(1,Math.round(base*(g.quarterLengthSeconds/600)));g.pendingPossession={team:t,result,points,beforeClock:g.scoreboardSeconds,clockSeconds:clock,remainingClockSeconds:Math.min(clock,g.scoreboardSeconds)} as Poss;g.activity="LIVE"}
function deadBall(g:Game){return g.quarterLengthSeconds===900?160+Math.floor(rnd(g)*81):25+Math.floor(rnd(g)*41)}
function finishPoss(g:Game){const p=g.pendingPossession as Poss|null;if(!p)return;if(p.points)score(g,p.team,p.points);g.possession=p.team===0?1:0;g.down=1;g.distance="10";g.ballSide="OWN";g.yardline=25;g.lastPlay=`${p.team===0?g.away.name:g.home.name} · ${p.result} · ${Math.floor(p.clockSeconds/60)}:${String(p.clockSeconds%60).padStart(2,"0")} possession`;g.pendingPossession=null;if(g.scoreboardSeconds<=0){g.scoreboardSeconds=0;finishPeriod(g);return}if(maybeBreak(g,p.beforeClock,g.scoreboardSeconds))return;g.deadBallSeconds=deadBall(g);g.activity="LIVE"}
function advanceGame(g:Game,syntheticSeconds:number){if(g.lifecycle!=="ACTIVE"||syntheticSeconds<=0)return;let rem=Math.floor(syntheticSeconds),guard=0;while(rem>0&&g.lifecycle==="ACTIVE"&&guard++<10000){if(g.operatorPaused)return;if(g.breakSeconds>0){const s=Math.min(rem,g.breakSeconds);g.breakSeconds-=s;g.elapsedSeconds+=s;rem-=s;if(g.breakSeconds===0)advancePeriod(g);continue}if(g.deadBallSeconds>0){const s=Math.min(rem,g.deadBallSeconds);g.deadBallSeconds-=s;g.elapsedSeconds+=s;rem-=s;continue}if(g.pendingPossession){const p=g.pendingPossession as Poss,s=Math.min(rem,p.remainingClockSeconds,g.scoreboardSeconds);p.remainingClockSeconds-=s;g.scoreboardSeconds-=s;g.elapsedSeconds+=s;rem-=s;if(p.remainingClockSeconds<=0||g.scoreboardSeconds<=0)finishPoss(g);continue}if(g.auto&&g.activity==="LIVE"){beginPoss(g);if(!g.pendingPossession)return;continue}g.elapsedSeconds+=rem;rem=0}}
function project(state:Game[],wallSeconds:number){const wall=Math.max(0,Math.min(21600,Math.floor(wallSeconds))),out=structuredClone(state);let maxSyn=0;for(const g of out){if(g.lifecycle!=="ACTIVE")continue;const sp=SPEEDS.includes(Number(g.speed))?Number(g.speed):1,syn=wall*sp;maxSyn=Math.max(maxSyn,syn);advanceGame(g,syn)}return{state:out,projected_wall_seconds:wall,max_projected_synthetic_seconds:maxSyn,catchup_capped:wallSeconds>wall}}
function archive(g:Game,disposition:string,reason:string){return{runId:g.runId,runNumber:g.runNumber,seedHex:g.seedHex,disposition,reason,lifecycle:g.lifecycle,awayFinal:total(g,0),homeFinal:total(g,1),quarterLengthSeconds:g.quarterLengthSeconds,elapsedSeconds:g.elapsedSeconds,archivedAt:now()}}
function resetRun(g:Game,newSeed:boolean,disposition:string,reason:string){const a=archive(g,disposition,reason);g.runHistory=[...(g.runHistory??[]),a].slice(-20);g.runNumber++;if(newSeed)g.seedHex=randHex(16);g.runId=runId(g.id,g.runNumber);g.rngState=seedWords(g.seedHex,g.id,g.runNumber);g.seedLocked=false;g.lifecycle="UNLAUNCHED";g.activity="UPCOMING";g.auto=false;g.operatorPaused=false;g.scoreboardSeconds=g.quarterLengthSeconds;g.elapsedSeconds=0;g.period="1st";g.activePeriod="1";g.otCount=0;g.speed=1;g.scores={"1":[0,0],"2":[0,0],"3":[0,0],"4":[0,0]};g.possession=0;g.ballSide="OWN";g.yardline=25;g.down=1;g.distance="10";g.breakSeconds=0;g.breakLabel="";g.deadBallSeconds=0;g.pendingPeriod="";g.pendingPossession=null;g.tvBreaksTaken=[];g.createdRunAt=now();g.launchedAt=null;g.completedAt=null;g.history=[];g.locked=false;g.lastPlay=newSeed?"Purged · new seed assigned · ready for launch":"Restarted · same seed preserved · ready for launch";return a}
function publicGame(g:Game){const c=structuredClone(g);for(const k of["seedHex","rngState","seedLocked","runHistory","history","awayPower1B","homePower1B","powerOverride","pendingPossession"])delete c[k];return c}
function reason(p:any){const r=String(p?.reason??"").trim();if(r.length<3)throw new Error("reason required");return r.slice(0,500)}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});const url=new URL(req.url),action=url.searchParams.get("api");if(!action)return new Response(null,{status:302,headers:{location:CONSOLE_URL,"cache-control":"no-store","x-robots-tag":"noindex,nofollow"}});try{const client=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}}),slug=url.searchParams.get("session")??"";
if(action==="create"&&req.method==="POST"){const operator=randHex(32),publicSlug=`w2v4-${randHex(8)}`;const{data,error}=await client.rpc("gamecast_v12_create_session",{p_public_slug:publicSlug,p_operator_token_hash:await sha256(operator),p_week_key:WEEK_KEY,p_engine_version:ENGINE_VERSION,p_data_version:DATA_VERSION,p_state:WEEK2.map(initialGame)});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row)throw new Error("session create returned no row");return json({...row,engine_version:ENGINE_VERSION,operator_token:operator},201)}
if(!slug)return json({error:"session required"},400);const{data:rows,error:readError}=await client.rpc("gamecast_v12_read_session",{p_slug:slug});if(readError)throw readError;const current=Array.isArray(rows)?rows[0]:rows;if(!current||current.week_key!==WEEK_KEY||!String(slug).startsWith("w2v4-"))return json({error:"V4 Week 2 session not found"},404);const dt=new Date(),wall=Math.max(0,Math.floor((dt.getTime()-Date.parse(current.last_advanced_at))/1000)),pr=project(current.state as Game[],wall),supplied=req.headers.get("x-operator-token")??"",isOperator=!!supplied&&await sha256(supplied)===current.operator_token_hash;
if(action==="read"&&req.method==="GET")return json({public_slug:slug,week_key:current.week_key,engine_version:ENGINE_VERSION,state:isOperator?pr.state:pr.state.map(publicGame),state_version:current.state_version,server_now:dt.toISOString(),projected_wall_seconds:pr.projected_wall_seconds,max_projected_synthetic_seconds:pr.max_projected_synthetic_seconds,catchup_capped:pr.catchup_capped,operator:isOperator});
if(action==="command"&&req.method==="POST"){if(!isOperator)return json({error:"operator token invalid"},403);const body=await req.json();if(Number(body.expected_version)!==Number(current.state_version))return json({error:"version conflict",current_version:current.state_version},409);const state=pr.state as Game[],g=state.find(x=>x.id===body.id);if(!g)return json({error:"game not found"},404);const c=String(body.command??""),p=body.payload??{};let event:any={runId:g.runId,seedHex:g.seedHex,engine_version:ENGINE_VERSION};
if(c==="quarter_length"){if(g.lifecycle!=="UNLAUNCHED")return json({error:"quarter length is locked after launch"},409);const q=Number(p.seconds);if(![600,900].includes(q))return json({error:"quarter length must be 600 or 900 seconds"},400);g.quarterLengthSeconds=q;g.scoreboardSeconds=q;g.lastPlay=`Quarter length set to ${q===600?"10:00":"15:00"}`}
else if(c==="launch"&&g.lifecycle==="UNLAUNCHED"){g.lifecycle="ACTIVE";g.activity="LIVE";g.elapsedSeconds=0;g.seedLocked=true;g.launchedAt=now();g.lastPlay=g.autoEligible?`Opening kickoff ready · ${g.runId}`:"Opening kickoff ready · manual mode; POWER 1B unavailable"}
else if(c==="auto"&&g.lifecycle==="ACTIVE"&&g.autoEligible){g.auto=!g.auto;g.activity=g.operatorPaused?"PAUSED":g.breakSeconds>0?"BREAK":"LIVE";g.lastPlay=g.auto?`AUTO running · ${g.speed}x`:"AUTO stopped by operator · Game Length continues in manual mode"}
else if(c==="speed"&&g.lifecycle==="ACTIVE"){const sp=Number(p.speed);if(!SPEEDS.includes(sp))return json({error:"speed must be 1x, 4x, 10x, or 50x"},400);if(!g.auto)return json({error:"acceleration is AUTO-only"},409);g.speed=sp;g.lastPlay=`AUTO speed set to ${sp}x`}
else if(c==="pause"&&g.lifecycle==="ACTIVE"){g.operatorPaused=!g.operatorPaused;g.activity=g.operatorPaused?"PAUSED":g.breakSeconds>0?"BREAK":"LIVE";g.lastPlay=g.operatorPaused?"Operator pause · simulation frozen":"Operator resume"}
else if(c==="clock_set"&&g.lifecycle==="ACTIVE"){const sec=Math.floor(Number(p.seconds));if(!Number.isFinite(sec)||sec<0||sec>g.quarterLengthSeconds)return json({error:"clock value outside quarter range"},400);event.beforeClock=g.scoreboardSeconds;g.scoreboardSeconds=sec;g.pendingPossession=null;g.deadBallSeconds=0;g.lastPlay=`Chairman clock correction · ${Math.floor(sec/60)}:${String(sec%60).padStart(2,"0")}`;event.afterClock=sec}
else if(c==="score"&&g.lifecycle==="ACTIVE"){const t=p.team===1?1:0,pts=[1,2,3,6,7,8].includes(Number(p.points))?Number(p.points):0;if(!pts)return json({error:"invalid score increment"},400);score(g,t,pts,"MANUAL");g.lastPlay=`Manual score · ${t===0?g.away.name:g.home.name} +${pts}`}
else if(c==="end"&&g.lifecycle==="ACTIVE"){g.lifecycle="FINAL_PENDING";g.activity="FINAL";g.auto=false;g.operatorPaused=false;g.pendingPossession=null;g.breakSeconds=0;g.deadBallSeconds=0;g.completedAt=now();g.lastPlay=`Operator ended game · ${total(g,0)}-${total(g,1)}`}
else if(c==="reopen_final"&&g.lifecycle==="FINAL_PENDING"){const r=reason(p);g.lifecycle="CORRECTION";g.activity="CORRECTION";g.auto=false;g.lastPlay=`Final reopened for correction · ${r}`;event.reason=r}
else if(c==="set_period_score"&&g.lifecycle==="CORRECTION"){const k=String(p.period??""),t=p.team===1?1:0,v=Math.floor(Number(p.value));if(!Object.prototype.hasOwnProperty.call(g.scores,k))return json({error:"period not found"},400);if(!Number.isFinite(v)||v<0||v>99)return json({error:"score must be 0-99"},400);const before=[...g.scores[k]],next:[number,number]=[Number(before[0]||0),Number(before[1]||0)];next[t]=v;g.scores[k]=next;g.lastPlay=`Score correction · ${k} · ${t===0?g.away.name:g.home.name} ${before[t]}→${v}`;event={...event,period:k,team:t,before:before[t],after:v}}
else if(c==="return_final"&&g.lifecycle==="CORRECTION"){const r=reason(p);g.lifecycle="FINAL_PENDING";g.activity="FINAL";g.lastPlay=`Correction complete · ${total(g,0)}-${total(g,1)} · ${r}`;event.reason=r}
else if(c==="lock"&&g.lifecycle==="FINAL_PENDING"){g.lifecycle="LOCKED";g.activity="FINAL";g.locked=true;g.lastPlay=`Result locked · ${total(g,0)}-${total(g,1)}`}
else if(c==="unlock"&&g.lifecycle==="LOCKED"){const r=reason(p);g.lifecycle="FINAL_PENDING";g.locked=false;g.lastPlay=`Result unlocked by Chairman · ${r}`;event.reason=r}
else if(c==="accept"&&g.lifecycle==="LOCKED"){g.lifecycle="READY";g.activity="FINAL";g.lastPlay=`Accepted result · READY for SEUD · ${total(g,0)}-${total(g,1)}`}
else if(c==="restart_same_seed"&&["ACTIVE","FINAL_PENDING","CORRECTION"].includes(g.lifecycle)){const r=reason(p),snapshot=structuredClone(g),a=resetRun(g,false,"RESTART_SAME_SEED",r);event={...event,reason:r,archived:a,snapshot}}
else if(c==="purge_new_seed"&&["UNLAUNCHED","ACTIVE","FINAL_PENDING","CORRECTION"].includes(g.lifecycle)){const r=reason(p),snapshot=structuredClone(g),a=resetRun(g,true,"PURGE_NEW_SEED",r);event={...event,reason:r,archived:a,snapshot,newRunId:g.runId,newSeedHex:g.seedHex}}
else return json({error:"command unavailable for current lifecycle"},409);
const stamp=now(),{data,error}=await client.rpc("gamecast_v12_update_session",{p_session_id:current.session_id,p_expected_version:current.state_version,p_state:state,p_stamp:stamp});if(error)throw error;const updated=Array.isArray(data)?data[0]:data;if(!updated)return json({error:"version conflict"},409);await client.rpc("gamecast_v12_insert_event",{p_session_id:current.session_id,p_state_version:updated.state_version,p_event_type:`V4_${c.toUpperCase()}`,p_game_id:g.id,p_payload:{...event,power_source:"POWER_1B",auto_eligible:g.autoEligible}});return json({state:updated.state,state_version:updated.state_version,last_advanced_at:updated.last_advanced_at,server_now:stamp,engine_version:ENGINE_VERSION})}
return json({error:"unsupported action"},400)}catch(e:any){console.error("gamecast-week2-v4",e?.code??"",e?.message??e,e?.details??"",e?.hint??"");return json({error:e?.message==="reason required"?"reason required":"internal error"},e?.message==="reason required"?400:500)}});
